version: '3.8'

services:
  frontend:
    image: node:18-alpine
    container_name: angular-frontend
    ports:
      - '4200:4200'
    working_dir: /usr/src/app
    command: npm run start
    volumes:
      - .:/usr/src/app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
  app-network:
    external: true  # Usar a mesma rede externa criada pelo backend